### ISSUE TITLE
containsKey or containsValue?

### ISSUE THREAD

**Issue by debayansaha102** [ClearControl/clearcontrol-lightsheet#11]
https://github.com/ClearControl/clearcontrol-lightsheet/blob/0b5732468dac8438f41e7e478283683c6da68842/src/clearcontrol/microscope/lightsheet/warehouse/containers/StackInterfaceContainer.java#L50

**Comment by haesleinhuepf** [comment]
Hey Deb,

thanks for pointing to this typo and the detailed description.

It was fixed with 51d21f4c720e6f84135fb28913d62b40f823dc01

Cheers,
Robert
